version: "3"

services:

  grpc-server:
    build: ./grpc-server
    volumes:
      - ./grpc-server:/go/src
    ports:
      - "50051:50051"
    
  grpc-client:
    build: ./grpc-client
    ports:
      - 3000:3000
    volumes:
      - ./grpc-client:/home/node/app

